variables:
  repository: fizzbuzz
  containerRegistry: fizzbuzz-connection
  isRelease: $[startsWith(variables['Build.SourceBranch'], 'refs/tags/')]

trigger:
  branches:
    include: [ '*' ]
  tags:
    include: [ '*.*.*' ]

stages:
- stage: Test
  jobs:
  - job: unit_tests
    pool:
      vmImage: 'ubuntu-latest'
    strategy:
      matrix:
        Python37:
          python.version: '3.7'
        Python38:
          python.version: '3.8'
    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '$(python.version)'
      displayName: 'Use Python $(python.version)'
    - script: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      displayName: 'Install dependencies'
    - script: |
        pytest
      displayName: 'Run tests'
- stage: Build
  condition: eq(variables.isRelease, true)
  jobs:
  - job:  build_docker_image
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - task: Docker@2
        displayName: Build and push an image to container registry
        inputs:
          command: buildAndPush
          repository: $(repository)
          containerRegistry: $(containerRegistry)
          tags: $(Build.SourceBranchName)
- stage: Deploy
  condition: eq(variables.isRelease, true)
  dependsOn: Build
  jobs:
    - job: deploy_flask_api
      pool:
        vmImage: 'ubuntu-latest'
      steps:
        - task: AzureWebAppContainer@1 # Add this at the end of your file
          inputs:
           azureSubscription: fizzbuzz-app
           appName: fizzbuzz-gf
           containers: fizzbuzz.azurecr.io/$(repository):$(Build.SourceBranchName)
