stages:
- stage: Test
  jobs:
  - job: unit_tests
    pool:
      vmImage: 'Ubuntu-16.04'
    steps:
    - script: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      displayName: 'Install dependencies'
    - script: |
        pytest
      displayName: 'Run tests'
